version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
      docker: 20
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Pre-build phase: Starting Docker daemon..."
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock &
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building Docker image using local Dockerfile..."
      - docker build -t my-image-repo:latest -f ./Dockerfile . # Using the local Dockerfile
      - docker tag my-image-repo:latest 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-image-repo:latest
  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-image-repo:latest

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
