version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" 
    volumes:
      - ./assets:/usr/share/nginx/html/assets 
      - ./index.html:/usr/share/nginx/html/index.html 
    depends_on:
      - app

  app:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    command: npm install && npm start
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb


