version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Maps port 80 in the container to port 8080 on the host
    volumes:
      - ./assets:/usr/share/nginx/html/assets # Mount the assets directory
      - ./index.html:/usr/share/nginx/html/index.html # Mount the index.html
    depends_on:
      - app

  app:
    image: node:16 # Example if you need a backend service like Node.js
    working_dir: /app
    volumes:
      - .:/app
    command: npm install && npm start
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb

